app:
  datasource:
    demo-db:
      jdbcUrl: jdbc:postgresql://localhost:5430/demoDB
      username: usr
      password: pwd
    flyway:
      enabled: true
      clean-on-validation-error: true
spring:
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
#server:
#  port: 8585